package test.java;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CheckSendPresentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkSendPresent() {
    // Test name: CheckSendPresent
    // Step # | name | target | value | comment
    // 1 | open | /rating |  | 
    driver.get("https://www.mamba.ru/rating");
    // 2 | setWindowSize | 976x807 |  | 
    driver.manage().window().setSize(new Dimension(976, 807));
    // 3 | click | css=.sc-1we9gs2-0:nth-child(7) .sc-vocpkn-2 > svg |  | 
    driver.findElement(By.cssSelector(".sc-1we9gs2-0:nth-child(7) .sc-vocpkn-2 > svg")).click();
    // 4 | click | name=stream-textarea |  | 
    driver.findElement(By.name("stream-textarea")).click();
    // 5 | type | name=stream-textarea | Привет, детка, хочешь меня? | 
    driver.findElement(By.name("stream-textarea")).sendKeys("Привет, детка, хочешь меня?");
    // 6 | click | css=.jBgVAf |  | 
    driver.findElement(By.cssSelector(".jBgVAf")).click();
    // 7 | selectFrame | index=0 |  | 
    driver.switchTo().frame(0);
    // 8 | selectFrame | index=0 |  | 
    driver.switchTo().frame(0);
    // 9 | type | id=cardnumber | 2200 1500 2222 2225 | 
    driver.findElement(By.id("cardnumber")).sendKeys("2200 1500 2222 2225");
    // 10 | click | id=expdate |  | 
    driver.findElement(By.id("expdate")).click();
    // 11 | type | id=expdate | 0130 | 
    driver.findElement(By.id("expdate")).sendKeys("0130");
    // 12 | type | id=cvc2 | 500 | 
    driver.findElement(By.id("cvc2")).sendKeys("500");
    // 13 | click | css=.js-button-submit |  | 
    driver.findElement(By.cssSelector(".js-button-submit")).click();
  }
}
