package test.java;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    // Test name: Login
    // Step # | name | target | value | comment
    // 1 | open | /ru |  | 
    driver.get("https://www.mamba.ru/ru");
    // 2 | setWindowSize | 1125x801 |  | 
    driver.manage().window().setSize(new Dimension(1125, 801));
    // 3 | click | xpath=//a[contains(text(),'Войти')] |  | 
    driver.findElement(By.xpath("//a[contains(text(),\'Войти\')]")).click();
    // 4 | click | xpath=//a[contains(text(),'Электронная почта')] |  | 
    driver.findElement(By.xpath("//a[contains(text(),\'Электронная почта\')]")).click();
    // 5 | type | xpath=//input[@name='login'] | eulerocircles@gmail.com | 
    driver.findElement(By.xpath("//input[@name=\'login\']")).sendKeys("eulerocircles@gmail.com");
    // 6 | click | xpath=//input[@name='password'] |  | 
    driver.findElement(By.xpath("//input[@name=\'password\']")).click();
    // 7 | type | xpath=//input[@name='password'] | ncT4xWCF | 
    driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("ncT4xWCF");
    // 8 | click | xpath=//input[@value='Войти'] |  | 
    driver.findElement(By.xpath("//input[@value=\'Войти\']")).click();
    // 9 | runScript | window.scrollTo(0,0) |  | 
    js.executeScript("window.scrollTo(0,0)");
    // 10 | runScript | window.scrollTo(0,0) |  | 
    js.executeScript("window.scrollTo(0,0)");
  }
}
