package test.java;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SwipesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void swipes() {
    // Test name: Swipes
    // Step # | name | target | value | comment
    // 1 | open | /rating |  | 
    driver.get("https://www.mamba.ru/rating");
    // 2 | setWindowSize | 1012x809 |  | 
    driver.manage().window().setSize(new Dimension(1012, 809));
    // 3 | click | css=.sc-18s0odj-0 > svg |  | 
    driver.findElement(By.cssSelector(".sc-18s0odj-0 > svg")).click();
    // 4 | click | css=.sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(2) > svg |  | 
    driver.findElement(By.cssSelector(".sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(2) > svg")).click();
    // 5 | click | css=.sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(2) > svg |  | 
    driver.findElement(By.cssSelector(".sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(2) > svg")).click();
    // 6 | mouseDown | css=.sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(3) > svg |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(3) > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 7 | mouseUp | css=.sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(3) path |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(3) path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 8 | click | css=.sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(3) > svg |  | 
    driver.findElement(By.cssSelector(".sc-1we9gs2-0:nth-child(7) .sc-vocpkn-3:nth-child(3) > svg")).click();
    // 9 | click | css=.sc-ph230s-10:nth-child(3) .sc-vocpkn-3:nth-child(3) path |  | 
    driver.findElement(By.cssSelector(".sc-ph230s-10:nth-child(3) .sc-vocpkn-3:nth-child(3) path")).click();
  }
}
