version: "3"
services:
  dragon:
    build:
      dockerfile: dragon.Dockerfile
    ports:
      - "8000:8443"
    env_file:
      - .env
    depends_on:
      - postgres

  killer:
    build:
      dockerfile: killer.Dockerfile
    ports:
      - "9000:8443"
    env_file:
      - .env
    depends_on:
      - dragon
      - postgres

  front:
    build:
      dockerfile: front.Dockerfile # путь к докер файлу
    ports:
      - "8443:443" # порты из докер файла
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NODE_ENV=production


  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5444:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
