package test.java;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogOutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logOut() {
    // Test name: LogOut
    // Step # | name | target | value | comment
    // 1 | open | /rating |  | 
    driver.get("https://www.mamba.ru/rating");
    // 2 | setWindowSize | 550x691 |  | 
    driver.manage().window().setSize(new Dimension(550, 691));
    // 3 | click | xpath=//div[@id='app-wrapper']/div/header/div[6]/a/img |  | 
    driver.findElement(By.xpath("//div[@id=\'app-wrapper\']/div/header/div[6]/a/img")).click();
    // 4 | click | css=.sc-qyouz1-0:nth-child(1) > svg > g > path:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".sc-qyouz1-0:nth-child(1) > svg > g > path:nth-child(1)")).click();
    // 5 | click | xpath=//div[@id='app']/div[3]/div/div/div/main/a/div/div[2] |  | 
    driver.findElement(By.xpath("//div[@id=\'app\']/div[3]/div/div/div/main/a/div/div[2]")).click();
    // 6 | click | xpath=//button[contains(.,'Выйти')] |  | 
    driver.findElement(By.xpath("//button[contains(.,\'Выйти\')]")).click();
  }
}
