package test.java;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProfileFillTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void profileFill() {
    // Test name: ProfileFill
    // Step # | name | target | value | comment
    // 1 | open | /profile/1817836140 |  | 
    driver.get("https://www.mamba.ru/profile/1817836140");
    // 2 | setWindowSize | 1087x807 |  | 
    driver.manage().window().setSize(new Dimension(1087, 807));
    // 3 | click | id=Fill-4 |  | 
    driver.findElement(By.id("Fill-4")).click();
    // 4 | runScript | window.scrollTo(0,0) |  | 
    js.executeScript("window.scrollTo(0,0)");
    // 5 | click | css=.hSNDiR |  | 
    driver.findElement(By.cssSelector(".hSNDiR")).click();
    // 6 | click | css=.sc-gbb4o6-2:nth-child(2) > .Parent-pghpvxv:nth-child(1) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".sc-gbb4o6-2:nth-child(2) > .Parent-pghpvxv:nth-child(1) .sc-i0mqd3-4")).click();
    // 7 | mouseOver | css=.sc-gbb4o6-2:nth-child(2) > .Parent-pghpvxv:nth-child(1) .sc-i0mqd3-4 |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".sc-gbb4o6-2:nth-child(2) > .Parent-pghpvxv:nth-child(1) .sc-i0mqd3-4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | mouseOut | css=.sc-gbb4o6-2:nth-child(2) > .Parent-pghpvxv:nth-child(1) .sc-i0mqd3-4 |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 9 | click | id=Average |  | 
    driver.findElement(By.id("Average")).click();
    // 10 | mouseOver | linkText=Детей нет, но хочу |  | 
    {
      WebElement element = driver.findElement(By.linkText("Детей нет, но хочу"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseOut | linkText=Детей нет, но хочу |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | click | css=.Parent-pghpvxv:nth-child(4) .sc-mvl5r7-6 |  | 
    driver.findElement(By.cssSelector(".Parent-pghpvxv:nth-child(4) .sc-mvl5r7-6")).click();
    // 13 | mouseOver | css=.Parent-pghpvxv:nth-child(4) .sc-mvl5r7-6 |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".Parent-pghpvxv:nth-child(4) .sc-mvl5r7-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | css=.Parent-pghpvxv:nth-child(4) .sc-mvl5r7-6 |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | click | name=weight |  | 
    driver.findElement(By.name("weight")).click();
    // 16 | select | name=weight | label=125 кг (276 lb) | 
    {
      WebElement dropdown = driver.findElement(By.name("weight"));
      dropdown.findElement(By.xpath("//option[. = '125 кг (276 lb)']")).click();
    }
    // 17 | click | css=option:nth-child(87) |  | 
    driver.findElement(By.cssSelector("option:nth-child(87)")).click();
    // 18 | click | css=.sc-n1mfaw-0 |  | 
    driver.findElement(By.cssSelector(".sc-n1mfaw-0")).click();
    // 19 | click | css=.Parent-pghpvxv:nth-child(5) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".Parent-pghpvxv:nth-child(5) .sc-i0mqd3-4")).click();
    // 20 | click | css=.sc-nd8xks-1:nth-child(5) |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(5)")).click();
    // 21 | click | css=.sc-nd8xks-1:nth-child(4) |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(4)")).click();
    // 22 | click | css=.sc-nd8xks-1:nth-child(3) |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(3)")).click();
    // 23 | click | css=.sc-n1mfaw-0 |  | 
    driver.findElement(By.cssSelector(".sc-n1mfaw-0")).click();
    // 24 | mouseOver | css=.sc-n1mfaw-0 |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".sc-n1mfaw-0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 25 | click | css=.Parent-pghpvxv:nth-child(6) .sc-i0mqd3-0 > svg |  | 
    driver.findElement(By.cssSelector(".Parent-pghpvxv:nth-child(6) .sc-i0mqd3-0 > svg")).click();
    // 26 | mouseOver | css=.Parent-pghpvxv:nth-child(6) .sc-i0mqd3-0 > svg |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".Parent-pghpvxv:nth-child(6) .sc-i0mqd3-0 > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 27 | mouseOut | css=.Parent-pghpvxv:nth-child(6) .sc-i0mqd3-0 > svg |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 28 | click | id=GiveUp |  | 
    driver.findElement(By.id("GiveUp")).click();
    // 29 | click | css=.Parent-pghpvxv:nth-child(7) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".Parent-pghpvxv:nth-child(7) .sc-i0mqd3-4")).click();
    // 30 | click | id=Yes |  | 
    driver.findElement(By.id("Yes")).click();
    // 31 | mouseOver | linkText=Живу с приятелем или с подругой |  | 
    {
      WebElement element = driver.findElement(By.linkText("Живу с приятелем или с подругой"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 32 | mouseOut | linkText=Живу с приятелем или с подругой |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
