package test.java;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    // Test name: Search
    // Step # | name | target | value | comment
    // 1 | open | /rating |  | 
    driver.get("https://www.mamba.ru/rating");
    // 2 | setWindowSize | 1018x814 |  | 
    driver.manage().window().setSize(new Dimension(1018, 814));
    // 3 | click | id=Fill-11 |  | 
    driver.findElement(By.id("Fill-11")).click();
    // 4 | click | css=.sc-102uidy-0:nth-child(3) .sc-s1o73v-0 |  | 
    driver.findElement(By.cssSelector(".sc-102uidy-0:nth-child(3) .sc-s1o73v-0")).click();
    // 5 | click | css=.sc-qyouz1-0:nth-child(1) > svg > path |  | 
    driver.findElement(By.cssSelector(".sc-qyouz1-0:nth-child(1) > svg > path")).click();
    // 6 | click | css=.sc-i0mqd3-11:nth-child(3) > .sc-i0mqd3-13:nth-child(1) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".sc-i0mqd3-11:nth-child(3) > .sc-i0mqd3-13:nth-child(1) .sc-i0mqd3-4")).click();
    // 7 | click | css=.sc-nd8xks-1:nth-child(2) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(2) .sc-n4vlnf-1")).click();
    // 8 | click | css=.sc-nd8xks-1:nth-child(3) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(3) .sc-n4vlnf-1")).click();
    // 9 | click | css=.sc-nd8xks-1:nth-child(4) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(4) .sc-n4vlnf-1")).click();
    // 10 | click | css=.sc-nd8xks-1:nth-child(5) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(5) .sc-n4vlnf-1")).click();
    // 11 | click | css=.sc-nd8xks-1:nth-child(6) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(6) .sc-n4vlnf-1")).click();
    // 12 | click | css=.sc-qyouz1-1 > svg |  | 
    driver.findElement(By.cssSelector(".sc-qyouz1-1 > svg")).click();
    // 13 | click | css=.sc-i0mqd3-11:nth-child(3) > .sc-i0mqd3-13:nth-child(5) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".sc-i0mqd3-11:nth-child(3) > .sc-i0mqd3-13:nth-child(5) .sc-i0mqd3-4")).click();
    // 14 | click | css=.sc-nd8xks-1:nth-child(6) |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(6)")).click();
    // 15 | click | css=.sc-nd8xks-1:nth-child(1) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(1) .sc-n4vlnf-1")).click();
    // 16 | click | css=.sc-nd8xks-1:nth-child(9) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(9) .sc-n4vlnf-1")).click();
    // 17 | click | css=.sc-nd8xks-1:nth-child(3) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(3) .sc-n4vlnf-1")).click();
    // 18 | click | css=g:nth-child(1) > g > g > g > path |  | 
    driver.findElement(By.cssSelector("g:nth-child(1) > g > g > g > path")).click();
    // 19 | click | css=.NsYAO:nth-child(6) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".NsYAO:nth-child(6) .sc-i0mqd3-4")).click();
    // 20 | click | css=.sc-nd8xks-1:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(1)")).click();
    // 21 | click | css=.sc-nd8xks-1:nth-child(2) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(2) .sc-n4vlnf-1")).click();
    // 22 | click | css=g:nth-child(1) > g > g > g > path |  | 
    driver.findElement(By.cssSelector("g:nth-child(1) > g > g > g > path")).click();
    // 23 | click | css=.sc-i0mqd3-13:nth-child(7) .sc-i0mqd3-4 |  | 
    driver.findElement(By.cssSelector(".sc-i0mqd3-13:nth-child(7) .sc-i0mqd3-4")).click();
    // 24 | click | css=.sc-nd8xks-1:nth-child(3) .sc-n4vlnf-1 |  | 
    driver.findElement(By.cssSelector(".sc-nd8xks-1:nth-child(3) .sc-n4vlnf-1")).click();
    // 25 | click | css=g:nth-child(1) > g > g > g > path |  | 
    driver.findElement(By.cssSelector("g:nth-child(1) > g > g > g > path")).click();
    // 26 | click | css=.sc-n1mfaw-0 |  | 
    driver.findElement(By.cssSelector(".sc-n1mfaw-0")).click();
  }
}
