openapi: 3.0.3
info:
  title: D&D killer service
  description: SOA Lab 1
  version: 1.0.0
servers:
  - url: 'https://localhost:1234/api/v1'
tags:
  - name: Killers
    description: Everything about Killers
paths:
  /killers/teams/create/{team-name}/{team-size}/{start-cave-id}:
    post:
      summary: Create a new dragon slayer team and save it in the database
      description: Create a new dragon slayer team and save it in the database
      tags:
        - Killers
      parameters:
        - name: team-name
          in: path
          required: true
          schema:
            type: string
            example: big killers
        - name: team-size
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 2
        - name: start-cave-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 2
      responses:
        '200':
          description: Successful operation returns team id
          content:
            application/json:
              schema:
                type: integer
                format: int64
                example: 10
        '400':
          description: Invalid args supplied
          content:
            application/json:
              schema:
                $ref: './DragonService.yaml#/components/schemas/Error400'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './DragonService.yaml#/components/schemas/Error500'

  /killers/team/{team-id}/move/{cave-id}:
    put:
      summary: Send a team of dragon slayers to the specified cave
      description: Send a team of dragon slayers to the specified cave
      parameters:
        - name: team-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            exclusiveMinimum: true
            example: 1
        - name: cave-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            exclusiveMinimum: true
            example: 2
      tags:
        - Killers
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid args supplied
          content:
            application/json:
              schema:
                $ref: './DragonService.yaml#/components/schemas/Error400'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './DragonService.yaml#/components/schemas/Error500'
